# BASE_URL=http://localhost:3000/api
# BASE_URL=http://gateway.gateway-api.orb.local:3000

# agregar en el readme que hay que hacer un npm install en cada carpeta y hay que hacer el npx prisma migrate dev --name init

### Create user
POST http://gateway.gateway-api.orb.local:3000/api/signup
content-type: application/json

{
  "name": "Roberto",
  "username": "rsbmk",
  "password": "rsbmk123",
  "email": "rsbmk@gmail.com",
  "ege": 23
}

### Sign In
POST http://gateway.gateway-api.orb.local:3000/api/signin
content-type: application/json

{
  "username": "rsbmk",
  "password": "rsbmk123"
}

### Test auth
GET http://gateway.gateway-api.orb.local:3000/games
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZWdlIjoyMywibmFtZSI6IlJvYmVydG8iLCJlbWFpbCI6InJzYm1rQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnNibWsiLCJzdGF0ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwiaWF0IjoxNzAxNjQzNTY3LCJleHAiOjE3MDE3Mjk5Njd9.7mXwuwu8X4vd-n3sHIKCZEB22UR6ijTGQ6ZAdyO9E0U