GET http://gateway.gateway-api.orb.local:3000/users/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZWdlIjoyMywibmFtZSI6IlJvYmVydG8iLCJlbWFpbCI6InJzYm1rQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnNibWsiLCJzdGF0ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwiaWF0IjoxNzAxNjQzNTY3LCJleHAiOjE3MDE3Mjk5Njd9.7mXwuwu8X4vd-n3sHIKCZEB22UR6ijTGQ6ZAdyO9E0U

### update user
PATCH  http://gateway.gateway-api.orb.local:3000/users/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZWdlIjoyMywibmFtZSI6IlJvYmVydG8iLCJlbWFpbCI6InJzYm1rQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnNibWsiLCJzdGF0ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwiaWF0IjoxNzAxNjQzNTY3LCJleHAiOjE3MDE3Mjk5Njd9.7mXwuwu8X4vd-n3sHIKCZEB22UR6ijTGQ6ZAdyO9E0U

{
  "name": "Samuel"
}

### delete user
DELETE http://gateway.gateway-api.orb.local:3000/users/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZWdlIjoyMywibmFtZSI6IlJvYmVydG8iLCJlbWFpbCI6InJzYm1rQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnNibWsiLCJzdGF0ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwiaWF0IjoxNzAxNjQzNTY3LCJleHAiOjE3MDE3Mjk5Njd9.7mXwuwu8X4vd-n3sHIKCZEB22UR6ijTGQ6ZAdyO9E0U
