# http://games.gateway-api.orb.local:3000 game -> url

# http://gateway.gateway-api.orb.local:3000 gateway -> url

### Get all games (GET /games) through gateway

GET http://gateway.gateway-api.orb.local:3000/games
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZWdlIjoyMywibmFtZSI6IlJvYmVydG8iLCJlbWFpbCI6InJzYm1rQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnNibWsiLCJzdGF0ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwiaWF0IjoxNzAxNjQzNTY3LCJleHAiOjE3MDE3Mjk5Njd9.7mXwuwu8X4vd-n3sHIKCZEB22UR6ijTGQ6ZAdyO9E0U

### GET one game (GET /games/:id) through gateway

GET http://gateway.gateway-api.orb.local:3000/games/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZWdlIjoyMywibmFtZSI6IlJvYmVydG8iLCJlbWFpbCI6InJzYm1rQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnNibWsiLCJzdGF0ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwiaWF0IjoxNzAxNjQzNTY3LCJleHAiOjE3MDE3Mjk5Njd9.7mXwuwu8X4vd-n3sHIKCZEB22UR6ijTGQ6ZAdyO9E0U

### Create a game (POST /games) through gateway
POST http://gateway.gateway-api.orb.local:3000/games
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZWdlIjoyMywibmFtZSI6IlJvYmVydG8iLCJlbWFpbCI6InJzYm1rQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoicnNibWsiLCJzdGF0ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwidXBkYXRlZEF0IjoiMjAyMy0xMi0wM1QyMjo0NDoxMi42OTRaIiwiaWF0IjoxNzAxNjQzNTY3LCJleHAiOjE3MDE3Mjk5Njd9.7mXwuwu8X4vd-n3sHIKCZEB22UR6ijTGQ6ZAdyO9E0U

{
    "name": "New Game",
    "description": "New Game Description",
    "urlImg": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ubisoft.com%2Fen-us%2Fgame%2"
}